### ISSUE TITLE
Add support for line breaks.

### ISSUE THREAD

**Issue by Varpie** [lpil/jot#19]
Djot supports [line breaks](https://djot.net/syntax#line-break), in a slightly different way that Markdown does: instead of double space, it uses `\` followed by a newline.

Since it is a frequent thing to use, it would be good to add support for those.

**Comment by Varpie** [comment]
I have encountered a bug related to this:
```
The `code` is\
on multiple lines.
```
results in
```html
is
<br>
The
<code>code</code>
on multiple lines.
```

The expected result is (modulo some whitespace)
```html
The <code>code</code> is<br>
on multiple lines.
```

**Comment by lpil** [comment]
Could you open an issue for that please @Varpie 💜

**Comment by Varpie** [comment]
Done (see #21)
