### ISSUE TITLE
Rendering the README example fails to produce the same as `djot.js`

### ISSUE THREAD

**Issue by erikareads** [lpil/jot#2]
Calling `jot.to_html` on the example:

```djot
# Hello, Joe!

This is a [Djot][djot] document.

[djot]: https://www.djot.net/
```

Produces incorrect html relative to `djot.js`.
Running `jot` 0.2.0 produces:

```
<h1 id="Hello,-Joe">Hello, Joe!</h1>
<p><a href="https://www.djot.net/">Djot</a> document.</p>
```

Compared to running `djot.js`:

```
<section id="Hello-Joe">
<h1>Hello, Joe!</h1>
<p>This is a <a href="https://www.djot.net/">Djot</a> document.</p>
</section>
```

There seem to be three issues here, which I'll create individual issues for so that they can be tackled independently:

1. `jot` fails to create a `<section>` and attaches the `id` to the `h1` instead.
2. `jot` keeps a `,` in the `id`
3. The words "This is a " are missing from the paragraph.

**Comment by lpil** [comment]
Hello! We do not aim to produce the same HTML as djot.js, difference is intentional.
