### ISSUE TITLE
Section `id` is attached to header tag instead

### ISSUE THREAD

**Issue by erikareads** [lpil/jot#3]
As mentioned in #2, when rendering a header, djot wraps the header in a section tag that contains an id. That id is a sanitized version of the text of the header.

For example:

```djot
# Hello, Joe!
```

Rendered with `djot.js`:

```
<section id="Hello-Joe">
<h1>Hello, Joe!</h1>
</section>
```

Currently with `jot` 0.2.0, the id is attached to the header tag instead:

```
<h1 id="Hello,-Joe">Hello, Joe!</h1>
```

This was initially identified in #2.

**Comment by lpil** [comment]
Matching djot.js's output format is not a goal, instead this package uses a more conventional and easier to work with HTML format, so the id is in the intended place here.

**Comment by erikareads** [comment]
Would it be worth adding a note to that effect in the README?
